// This file is autogenerated by VESC Tool

#include "buffer.h"
#include "conf_general.h"
#include "confparser.h"

int32_t confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer[ind++] = (uint8_t)conf->controller_id;
	buffer_append_uint32(buffer, conf->send_can_status_rate_hz, &ind);
	buffer[ind++] = conf->can_baud_rate;
	buffer_append_int16(buffer, conf->max_bal_ch, &ind);
	buffer[ind++] = conf->dist_bal;
	buffer[ind++] = conf->balance_mode;
	buffer_append_int16(buffer, conf->cell_num, &ind);
	buffer_append_int16(buffer, conf->cell_first_index, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_start, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_end, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_start, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_end, &ind);
	buffer_append_float32_auto(buffer, conf->vc_charge_min, &ind);
	buffer_append_float32_auto(buffer, conf->vc_balance_min, &ind);
	buffer_append_float32_auto(buffer, conf->balance_max_current, &ind);
	buffer_append_float32_auto(buffer, conf->min_current_ah_wh_cnt, &ind);
	buffer_append_float32_auto(buffer, conf->min_current_sleep, &ind);
	buffer_append_float32_auto(buffer, conf->v_charge_detect, &ind);
	buffer_append_float16(buffer, conf->t_charge_max, 10, &ind);
	buffer[ind++] = conf->i_measure_mode;
	buffer_append_float32_auto(buffer, conf->ext_shunt_res, &ind);
	buffer_append_float32_auto(buffer, conf->ext_shunt_gain, &ind);
	buffer_append_float32_auto(buffer, conf->ext_pch_r_top, &ind);
	buffer_append_float32_auto(buffer, conf->ext_pch_r_bot, &ind);
	buffer_append_float32_auto(buffer, conf->max_charge_current, &ind);
	buffer_append_int32(buffer, conf->sleep_timeout_reset_ms, &ind);
	buffer_append_float32_auto(buffer, conf->soc_filter_const, &ind);
	buffer_append_float16(buffer, conf->t_bal_lim_start, 10, &ind);
	buffer_append_float16(buffer, conf->t_bal_lim_end, 10, &ind);
	buffer_append_float16(buffer, conf->t_charge_min, 10, &ind);
	buffer[ind++] = conf->t_charge_mon_en;

	return ind;
}

bool confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	conf->controller_id = buffer[ind++];
	conf->send_can_status_rate_hz = buffer_get_uint32(buffer, &ind);
	conf->can_baud_rate = buffer[ind++];
	conf->max_bal_ch = buffer_get_int16(buffer, &ind);
	conf->dist_bal = buffer[ind++];
	conf->balance_mode = buffer[ind++];
	conf->cell_num = buffer_get_int16(buffer, &ind);
	conf->cell_first_index = buffer_get_int16(buffer, &ind);
	conf->vc_balance_start = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_end = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_start = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_end = buffer_get_float32_auto(buffer, &ind);
	conf->vc_charge_min = buffer_get_float32_auto(buffer, &ind);
	conf->vc_balance_min = buffer_get_float32_auto(buffer, &ind);
	conf->balance_max_current = buffer_get_float32_auto(buffer, &ind);
	conf->min_current_ah_wh_cnt = buffer_get_float32_auto(buffer, &ind);
	conf->min_current_sleep = buffer_get_float32_auto(buffer, &ind);
	conf->v_charge_detect = buffer_get_float32_auto(buffer, &ind);
	conf->t_charge_max = buffer_get_float16(buffer, 10, &ind);
	conf->i_measure_mode = buffer[ind++];
	conf->ext_shunt_res = buffer_get_float32_auto(buffer, &ind);
	conf->ext_shunt_gain = buffer_get_float32_auto(buffer, &ind);
	conf->ext_pch_r_top = buffer_get_float32_auto(buffer, &ind);
	conf->ext_pch_r_bot = buffer_get_float32_auto(buffer, &ind);
	conf->max_charge_current = buffer_get_float32_auto(buffer, &ind);
	conf->sleep_timeout_reset_ms = buffer_get_int32(buffer, &ind);
	conf->soc_filter_const = buffer_get_float32_auto(buffer, &ind);
	conf->t_bal_lim_start = buffer_get_float16(buffer, 10, &ind);
	conf->t_bal_lim_end = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_min = buffer_get_float16(buffer, 10, &ind);
	conf->t_charge_mon_en = buffer[ind++];

	return true;
}

void confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->send_can_status_rate_hz = CONF_SEND_CAN_STATUS_RATE_HZ;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->max_bal_ch = CONF_MAX_BAL_CH;
	conf->dist_bal = CONF_DIST_BAL;
	conf->balance_mode = CONF_BALANCE_MODE;
	conf->cell_num = CONF_CELL_NUM;
	conf->cell_first_index = CONF_CELL_FIRST_INDEX;
	conf->vc_balance_start = CONF_BALANCE_START;
	conf->vc_balance_end = CONF_BALANCE_END;
	conf->vc_charge_start = CONF_CHARGE_START;
	conf->vc_charge_end = CONF_CHARGE_END;
	conf->vc_charge_min = CONF_CHARGE_MIN;
	conf->vc_balance_min = CONF_BALANCE_MIN;
	conf->balance_max_current = CONF_BALANCE_MAX_CURRENT;
	conf->min_current_ah_wh_cnt = CONF_MIN_CURRENT_AH_WH_CNT;
	conf->min_current_sleep = CONF_MIN_CURRENT_SLEEP;
	conf->v_charge_detect = CONF_V_CHARGE_DETECT;
	conf->t_charge_max = CONF_T_CHARGE_MAX;
	conf->i_measure_mode = CONF_I_MEASURE_MODE;
	conf->ext_shunt_res = CONF_EXT_SHUNT_RES;
	conf->ext_shunt_gain = CONF_EXT_SHUNT_GAIN;
	conf->ext_pch_r_top = CONF_EXT_PCH_R_TOP;
	conf->ext_pch_r_bot = CONF_EXT_PCH_R_BOTTOM;
	conf->max_charge_current = CONF_MAX_CHARGE_CURRENT;
	conf->sleep_timeout_reset_ms = CONF_SLEEP_TIMEOUT_MS;
	conf->soc_filter_const = CONF_SOC_FILTER_CONST;
	conf->t_bal_lim_start = CONF_T_BAL_LIM_START;
	conf->t_bal_lim_end = CONF_T_BAL_LIM_END;
	conf->t_charge_min = CONF_T_CHARGE_MIN;
	conf->t_charge_mon_en = CONF_T_CHARGE_MON_EN;
}

