# SEGGER RTT files.
SEGGERASMSRC =  $(CHIBIOS_CONTRIB)/ext/SEGGER/RTT/SEGGER_RTT_ASM_ARMv7M.s
SEGGERRTTCSRC = $(CHIBIOS_CONTRIB)/ext/SEGGER/RTT/SEGGER_RTT.c             \
                $(CHIBIOS_CONTRIB)/ext/SEGGER/RTT/SEGGER_RTT_printf.c	   \
                $(CHIBIOS_CONTRIB)/os/various/segger_bindings/RTT/SEGGER_RTT_streams.c
SEGGERRTTINC =  $(CHIBIOS_CONTRIB)/ext/SEGGER/RTT \
                $(CHIBIOS_CONTRIB)/os/various/segger_bindings/RTT


SEGGER_RTT_ACTIVE = 1

ALLASMSRC += $(SEGGERASMSRC)
ALLCSRC += $(SEGGERRTTCSRC)
ALLINC += $(SEGGERRTTINC)